export interface TacticalUnit {
  id: string;
  name: string;
  callsign: string;
  status: "ACTIVE" | "INACTIVE" | "DISABLED";
  power: number; // percentage
  sessionTime: string;
  signal: "STRONG" | "MODERATE" | "LOW" | "NO SIGNAL";
  performanceGauge: number; // percentage
  statusText: string;
  lat: number;
  lon: number;
  model: string;
  altitude: string;
  speed: string;
  frequency: string;
  cameraFeed: string;
  sector: string;
  // Screen coordinates for isometric NYC canvas view
  canvasX: number; // percentage 0-100
  canvasY: number; // percentage 0-100
}

export const TACTICAL_UNITS: TacticalUnit[] = [
  {
    id: "aec-4200",
    name: "AEC-4200-NYC",
    callsign: "VIPER-01",
    status: "ACTIVE",
    power: 80,
    sessionTime: "3HR 20MIN",
    signal: "MODERATE",
    performanceGauge: 62,
    statusText: "PREPARING PERFORMANCE DETAILS...",
    lat: 40.7033,
    lon: -74.017,
    model: "Skylark-IV Surveillance UAV",
    altitude: "1,240 FT AGL",
    speed: "42 KTS",
    frequency: "5.820 GHz ENC",
    cameraFeed: "EO/IR FLIR HD",
    sector: "Lower Manhattan / Battery Park",
    canvasX: 45.4,
    canvasY: 47.8,
  },
  {
    id: "iuh-305",
    name: "IUH-305-NYC",
    callsign: "RAVEN-04",
    status: "ACTIVE",
    power: 76,
    sessionTime: "2HR 10MIN",
    signal: "STRONG",
    performanceGauge: 71,
    statusText: "TELEMETRY STABLE // SENSORS NOMINAL",
    lat: 40.7075,
    lon: -74.009,
    model: "Vector-X Micro-UAV",
    altitude: "890 FT AGL",
    speed: "36 KTS",
    frequency: "2.440 GHz ENC",
    cameraFeed: "4K Dual Spectrum",
    sector: "Financial District / Wall St",
    canvasX: 72.0,
    canvasY: 52.4,
  },
  {
    id: "bds-230",
    name: "BDS-230-NYC",
    callsign: "GHOST-02",
    status: "ACTIVE",
    power: 65,
    sessionTime: "1HR 12MIN",
    signal: "STRONG",
    performanceGauge: 60,
    statusText: "OPTICAL TRACKING LOCK // PIER 17",
    lat: 40.7063,
    lon: -74.0031,
    model: "Skydio X2D Recon",
    altitude: "650 FT AGL",
    speed: "28 KTS",
    frequency: "5.180 GHz ENC",
    cameraFeed: "360° LiDAR + Optical",
    sector: "East River Marine Corridor",
    canvasX: 69.5,
    canvasY: 72.0,
  },
  {
    id: "apd-7100",
    name: "APD-7100-NYC",
    callsign: "SENTINEL-07",
    status: "ACTIVE",
    power: 88,
    sessionTime: "4HR 05MIN",
    signal: "MODERATE",
    performanceGauge: 78,
    statusText: "AIR DEFENSE LINK // AIS SYNCHRONIZED",
    lat: 40.7071,
    lon: -73.9903,
    model: "Watchkeeper X Tactical UAV",
    altitude: "2,400 FT AGL",
    speed: "64 KTS",
    frequency: "8.410 GHz X-BAND",
    cameraFeed: "Synthetic Aperture Radar",
    sector: "Brooklyn Navy Yard Sector",
    canvasX: 94.2,
    canvasY: 44.5,
  },
  {
    id: "bas-3100",
    name: "BAS-3100-NYC",
    callsign: "EAGLE-03",
    status: "ACTIVE",
    power: 92,
    sessionTime: "1HR 45MIN",
    signal: "STRONG",
    performanceGauge: 84,
    statusText: "PATROL GRID ACTIVE // HARBOR SOUTH",
    lat: 40.6995,
    lon: -74.015,
    model: "AeroVironment Puma 3 AE",
    altitude: "1,550 FT AGL",
    speed: "48 KTS",
    frequency: "4.990 GHz PUBLIC-SAFETY",
    cameraFeed: "Long-Range EO/IR Gimbal",
    sector: "Governors Island Approach",
    canvasX: 38.0,
    canvasY: 62.0,
  },
  {
    id: "icd-500",
    name: "ICD-500-NYC",
    callsign: "TALON-09",
    status: "INACTIVE",
    power: 14,
    sessionTime: "STANDBY",
    signal: "LOW",
    performanceGauge: 18,
    statusText: "DOCKED AT HUB 4 // FAST CHARGING",
    lat: 40.718,
    lon: -74.002,
    model: "SkyRanger R70 Tactical",
    altitude: "0 FT (PAD 4)",
    speed: "0 KTS",
    frequency: "STANDBY",
    cameraFeed: "OFFLINE",
    sector: "Midtown Charging Node",
    canvasX: 82.0,
    canvasY: 30.0,
  },
  {
    id: "mne-9420",
    name: "MNE-9420-NYC",
    callsign: "SHADOW-11",
    status: "DISABLED",
    power: 0,
    sessionTime: "OFFLINE",
    signal: "NO SIGNAL",
    performanceGauge: 0,
    statusText: "MAINTENANCE INTERVAL // ROTOR SERVICING",
    lat: 40.725,
    lon: -73.995,
    model: "Black Hornet Nano 3",
    altitude: "HANGAR B",
    speed: "0 KTS",
    frequency: "DISABLED",
    cameraFeed: "OFFLINE",
    sector: "Depot Maintenance Bay",
    canvasX: 60.0,
    canvasY: 20.0,
  },
];
